[[users]]
username = "spez"
communities = ["modnews", "modsupport"]
label = "Admin"
discord_webhook_url = "https://discord.com/api/webhooks/XXXXXXXX/XXXXXXXX"

[[users]]
username = "LackingAGoodName"
label = "Friend"
discord_webhook_url = "https://discord.com/api/webhooks/YYYYYYYY/YYYYYYYY"
exclude_comments = true

[[users]]
username = "SledgehammerGames"
discord_webhook_url = "https://discord.com/api/webhooks/ZZZZZZZZ/ZZZZZZZZ"
