[tool.poetry]
name = "snoopy"
version = "1.0.0"
description = "Redditor watching service which tracks specific user replies in a thread and notifies via Discord."
authors = ["Ethan C <EthanC@github.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
praw = "^6.5.1"
coloredlogs = "^10.0"
httpx = "^0.11.1"

[tool.poetry.dev-dependencies]
pylint = "^2.4.4"
black = "^19.10b0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
