[project]
name = "snoopy"
version = "3.0.0"
description = "Monitor users on Reddit and notify about post activity."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "environs>=14.3.0",
    "loguru>=0.7.3",
    "loguru-discord>=1.4.0",
    "praw>=7.8.1",
    "discord-clyde>=0.3.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "ruff>=0.13.1",
]

[tool.ruff]
fix = true
show-fixes = true

[tool.ruff.lint]
select = ["I"]

[tool.ruff.lint.isort]
split-on-trailing-comma = false
